language: node_js
node_js: 8
script: npm run dist && npm pack

if: tag IS blank

after_success:
  - bin/upload-zeus-artifact *.tgz "application/tar+npm"

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/f41c0b0c-c4de-11e7-b821-0a580a280838/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
