name: Create JIRA issue

on:
  issues:
    types: [labeled]

jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: vladanpaunovic/ga-jira-integration@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          JIRA_API_HOST: ${{secrets.JIRA_BASEURL}}
          JIRA_API_TOKEN: ${{secrets.JIRA_APITOKEN}}
          JIRA_EMAIL: ${{secrets.JIRA_USEREMAIL}}
          TRIGGER_LABEL: jira
          JIRA_PROJECT_ID: WTEST
          JIRA_ISSUE_NAME: Story
          after-jira-issue-message: |-
            WIP
